version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready" ,"-q", "-U", "root"] 
      timeout: 2s
      retries: 2
    cap_add:
      - SYS_NICE
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] 
      timeout: 2s
      retries: 2
